# This file configures the titles and iconography of pages within the application

[pages]
order = ["solpool_insight.py", "1_Data_Explorer.py", "2_Predictions.py", "3_Risk_Assessment.py", "4_NLP_Reports.py", "4_Technology_Explained.py", "5_API_Documentation.py"]

[pages.solpool_insight]
title = "SolPool Insight"
icon = "ğŸŒŠ"

[pages."1_Data_Explorer"]
icon = "ğŸ“Š"

[pages."2_Predictions"]
icon = "ğŸ”®"

[pages."3_Risk_Assessment"]
icon = "âš ï¸"

[pages."4_NLP_Reports"]
icon = "ğŸ“"

[pages."4_Technology_Explained"]
icon = "ğŸ’»"

[pages."5_API_Documentation"]
icon = "ğŸ”Œ"
